// WARNING: Do not modify this file manually because it is autogenerated by "./bin/update_icons.sh".
// To update this file, run "./bin/update_icons.sh" from the root folder of this repo.
import BacteriaCultureIcon from "./BacteriaCultureIcon";
import CZIDLogoReversed from "./CZIDLogoReversed";
import IconAlert from "./IconAlert";
import IconAlertSmall from "./IconAlertSmall";
import IconAlignmentSmall from "./IconAlignmentSmall";
import IconAnalyzeFigure from "./IconAnalyzeFigure";
import IconAnnotationCheck from "./IconAnnotationCheck";
import IconAnnotationCross from "./IconAnnotationCross";
import IconAnnotationOutline from "./IconAnnotationOutline";
import IconAnnotationQuestion from "./IconAnnotationQuestion";
import IconArrowDownSmall from "./IconArrowDownSmall";
import IconArrowPipelineStage from "./IconArrowPipelineStage";
import IconArrowRight from "./IconArrowRight";
import IconArrowUpSmall from "./IconArrowUpSmall";
import IconBarChartHorizontal3Small from "./IconBarChartHorizontal3Small";
import IconBiohubLogo from "./IconBiohubLogo";
import IconBlast from "./IconBlast";
import IconBlastSmall from "./IconBlastSmall";
import IconChartSmall from "./IconChartSmall";
import IconCheckSmall from "./IconCheckSmall";
import IconClose from "./IconClose";
import IconCloseSmall from "./IconCloseSmall";
import IconConsensusSmall from "./IconConsensusSmall";
import IconContigSmall from "./IconContigSmall";
import IconCopySmall from "./IconCopySmall";
import IconCoverage from "./IconCoverage";
import IconCziLogo from "./IconCziLogo";
import IconDoubleQuotes from "./IconDoubleQuotes";
import IconDownload from "./IconDownload";
import IconDownloadSmall from "./IconDownloadSmall";
import IconHelp from "./IconHelp";
import IconInfo from "./IconInfo";
import IconInfoSmall from "./IconInfoSmall";
import IconListSmall from "./IconListSmall";
import IconLoading from "./IconLoading";
import IconMapSmall from "./IconMapSmall";
import IconMatchesFigure from "./IconMatchesFigure";
import IconMinusSmall from "./IconMinusSmall";
import IconMobileNavClose from "./IconMobileNavClose";
import IconPercentageSmall from "./IconPercentageSmall";
import IconPhyloTreeSmall from "./IconPhyloTreeSmall";
import IconPlusCircleSmall from "./IconPlusCircleSmall";
import IconPlusSmall from "./IconPlusSmall";
import IconSampleFigure from "./IconSampleFigure";
import IconSave from "./IconSave";
import IconSearch from "./IconSearch";
import IconShare from "./IconShare";
import IconSubmitArrow from "./IconSubmitArrow";
import IconSuccess from "./IconSuccess";
import IconSuccessSmall from "./IconSuccessSmall";
import IconTableSmall from "./IconTableSmall";
import IconTempSmall from "./IconTempSmall";
import IconTreeSmall from "./IconTreeSmall";
import IconUploadFigure from "./IconUploadFigure";
import LogoLockupColor from "./LogoLockupColor";
import LogoLockupReversed from "./LogoLockupReversed";
import LogoMarkColor from "./LogoMarkColor";
import LogoMarkReversed from "./LogoMarkReversed";
import SortIcon from "./SortIcon";

export const ICONS_TAXONOMY = {
  CUSTOM: {
    BacteriaCultureIcon,
    IconAlert,
    IconAlertSmall,
    IconAlignmentSmall,
    IconAnalyzeFigure,
    IconAnnotationCheck,
    IconAnnotationCross,
    IconAnnotationOutline,
    IconAnnotationQuestion,
    IconArrowDownSmall,
    IconArrowPipelineStage,
    IconArrowUpSmall,
    IconBarChartHorizontal3Small,
    IconBlast,
    IconBlastSmall,
    IconChartSmall,
    IconCheckSmall,
    IconClose,
    IconCloseSmall,
    IconConsensusSmall,
    IconContigSmall,
    IconCopySmall,
    IconCoverage,
    IconDoubleQuotes,
    IconDownload,
    IconDownloadSmall,
    IconHelp,
    IconInfo,
    IconInfoSmall,
    IconListSmall,
    IconLoading,
    IconMapSmall,
    IconMatchesFigure,
    IconMinusSmall,
    IconMobileNavClose,
    IconPercentageSmall,
    IconPhyloTreeSmall,
    IconPlusCircleSmall,
    IconPlusSmall,
    IconSampleFigure,
    IconSave,
    IconSearch,
    IconShare,
    IconSubmitArrow,
    IconSuccess,
    IconSuccessSmall,
    IconTableSmall,
    IconTempSmall,
    IconTreeSmall,
    IconUploadFigure,
    SortIcon,
  },
  FONT_AWESOME: {
    IconArrowRight,
  },
  LOGO: {
    IconBiohubLogo,
    IconCziLogo,
    LogoLockupColor,
    LogoMarkColor,
  },
  LOGO_REVERSED: {
    CZIDLogoReversed,
    LogoLockupReversed,
    LogoMarkReversed,
  },
};

export {
  BacteriaCultureIcon,
  CZIDLogoReversed,
  IconAlert,
  IconAlertSmall,
  IconAlignmentSmall,
  IconAnalyzeFigure,
  IconAnnotationCheck,
  IconAnnotationCross,
  IconAnnotationOutline,
  IconAnnotationQuestion,
  IconArrowDownSmall,
  IconArrowPipelineStage,
  IconArrowRight,
  IconArrowUpSmall,
  IconBarChartHorizontal3Small,
  IconBiohubLogo,
  IconBlast,
  IconBlastSmall,
  IconChartSmall,
  IconCheckSmall,
  IconClose,
  IconCloseSmall,
  IconConsensusSmall,
  IconContigSmall,
  IconCopySmall,
  IconCoverage,
  IconCziLogo,
  IconDoubleQuotes,
  IconDownload,
  IconDownloadSmall,
  IconHelp,
  IconInfo,
  IconInfoSmall,
  IconListSmall,
  IconLoading,
  IconMapSmall,
  IconMatchesFigure,
  IconMinusSmall,
  IconMobileNavClose,
  IconPercentageSmall,
  IconPhyloTreeSmall,
  IconPlusCircleSmall,
  IconPlusSmall,
  IconSampleFigure,
  IconSave,
  IconSearch,
  IconShare,
  IconSubmitArrow,
  IconSuccess,
  IconSuccessSmall,
  IconTableSmall,
  IconTempSmall,
  IconTreeSmall,
  IconUploadFigure,
  LogoLockupColor,
  LogoLockupReversed,
  LogoMarkColor,
  LogoMarkReversed,
  SortIcon,
};
