// WARNING: Do not modify this file manually because it is autogenerated by "./bin/update_icons.sh".
// To update this file, run "./bin/update_icons.sh" from the root folder of this repo.
import BacteriaCultureIcon from "./BacteriaCultureIcon";
import CZIDLogoReversed from "./CZIDLogoReversed";
import IconAlert from "./IconAlert";
import IconAlertSmall from "./IconAlertSmall";
import IconAlignmentSmall from "./IconAlignmentSmall";
import IconAnalyzeFigure from "./IconAnalyzeFigure";
import IconAnnotationCheck from "./IconAnnotationCheck";
import IconAnnotationCross from "./IconAnnotationCross";
import IconAnnotationOutline from "./IconAnnotationOutline";
import IconAnnotationQuestion from "./IconAnnotationQuestion";
import IconArrowDownSmall from "./IconArrowDownSmall";
import IconArrowPipelineStage from "./IconArrowPipelineStage";
import IconArrowRight from "./IconArrowRight";
import IconArrowUpSmall from "./IconArrowUpSmall";
import IconBackgroundModel from "./IconBackgroundModel";
import IconBarChartHorizontal3Small from "./IconBarChartHorizontal3Small";
import IconBiohubLogo from "./IconBiohubLogo";
import IconBlast from "./IconBlast";
import IconBlastSmall from "./IconBlastSmall";
import IconBrowserSmall from "./IconBrowserSmall";
import IconChartSmall from "./IconChartSmall";
import IconCheckSmall from "./IconCheckSmall";
import IconClose from "./IconClose";
import IconCloseSmall from "./IconCloseSmall";
import IconConsensusSmall from "./IconConsensusSmall";
import IconContigSmall from "./IconContigSmall";
import IconCopySmall from "./IconCopySmall";
import IconCoverage from "./IconCoverage";
import IconCziLogo from "./IconCziLogo";
import IconDoubleQuotes from "./IconDoubleQuotes";
import IconDownload from "./IconDownload";
import IconDownloadSmall from "./IconDownloadSmall";
import IconFilters from "./IconFilters";
import IconHeatmap from "./IconHeatmap";
import IconHeatmapPrivate from "./IconHeatmapPrivate";
import IconHeatmapPublic from "./IconHeatmapPublic";
import IconHelp from "./IconHelp";
import IconInfo from "./IconInfo";
import IconInfoPanel from "./IconInfoPanel";
import IconInfoSmall from "./IconInfoSmall";
import IconInsightSmall from "./IconInsightSmall";
import IconListSmall from "./IconListSmall";
import IconLoading from "./IconLoading";
import IconMapSmall from "./IconMapSmall";
import IconMatchesFigure from "./IconMatchesFigure";
import IconMember from "./IconMember";
import IconMemberSmall from "./IconMemberSmall";
import IconMinusSmall from "./IconMinusSmall";
import IconMobileNavClose from "./IconMobileNavClose";
import IconNextcladeLarge from "./IconNextcladeLarge";
import IconPercentageSmall from "./IconPercentageSmall";
import IconPhyloTree from "./IconPhyloTree";
import IconPhyloTreePrivate from "./IconPhyloTreePrivate";
import IconPhyloTreePublic from "./IconPhyloTreePublic";
import IconPhyloTreeSmall from "./IconPhyloTreeSmall";
import IconPlusCircleSmall from "./IconPlusCircleSmall";
import IconPlusSmall from "./IconPlusSmall";
import IconPrivateSmall from "./IconPrivateSmall";
import IconPublicSmall from "./IconPublicSmall";
import IconRefresh from "./IconRefresh";
import IconSample from "./IconSample";
import IconSampleFigure from "./IconSampleFigure";
import IconSamplePrivate from "./IconSamplePrivate";
import IconSamplePublic from "./IconSamplePublic";
import IconSave from "./IconSave";
import IconSearch from "./IconSearch";
import IconShare from "./IconShare";
import IconSubmitArrow from "./IconSubmitArrow";
import IconSuccess from "./IconSuccess";
import IconSuccessSmall from "./IconSuccessSmall";
import IconTableSmall from "./IconTableSmall";
import IconTempSmall from "./IconTempSmall";
import IconTreeSmall from "./IconTreeSmall";
import IconUploadFigure from "./IconUploadFigure";
import IconViewSmall from "./IconViewSmall";
import LogoLockupColor from "./LogoLockupColor";
import LogoLockupReversed from "./LogoLockupReversed";
import LogoMarkColor from "./LogoMarkColor";
import LogoMarkReversed from "./LogoMarkReversed";
import SortIcon from "./SortIcon";

export const ICONS_TAXONOMY = {
  CUSTOM: {
    BacteriaCultureIcon,
    IconAlert,
    IconAlertSmall,
    IconAlignmentSmall,
    IconAnalyzeFigure,
    IconAnnotationCheck,
    IconAnnotationCross,
    IconAnnotationOutline,
    IconAnnotationQuestion,
    IconArrowDownSmall,
    IconArrowPipelineStage,
    IconArrowUpSmall,
    IconBackgroundModel,
    IconBarChartHorizontal3Small,
    IconBlast,
    IconBlastSmall,
    IconBrowserSmall,
    IconChartSmall,
    IconCheckSmall,
    IconClose,
    IconCloseSmall,
    IconConsensusSmall,
    IconContigSmall,
    IconCopySmall,
    IconCoverage,
    IconDoubleQuotes,
    IconDownload,
    IconDownloadSmall,
    IconFilters,
    IconHeatmap,
    IconHeatmapPrivate,
    IconHeatmapPublic,
    IconHelp,
    IconInfo,
    IconInfoPanel,
    IconInfoSmall,
    IconInsightSmall,
    IconListSmall,
    IconLoading,
    IconMapSmall,
    IconMatchesFigure,
    IconMember,
    IconMemberSmall,
    IconMinusSmall,
    IconMobileNavClose,
    IconNextcladeLarge,
    IconPercentageSmall,
    IconPhyloTree,
    IconPhyloTreePrivate,
    IconPhyloTreePublic,
    IconPhyloTreeSmall,
    IconPlusCircleSmall,
    IconPlusSmall,
    IconPrivateSmall,
    IconPublicSmall,
    IconRefresh,
    IconSample,
    IconSampleFigure,
    IconSamplePrivate,
    IconSamplePublic,
    IconSave,
    IconSearch,
    IconShare,
    IconSubmitArrow,
    IconSuccess,
    IconSuccessSmall,
    IconTableSmall,
    IconTempSmall,
    IconTreeSmall,
    IconUploadFigure,
    IconViewSmall,
    SortIcon,
  },
  FONT_AWESOME: {
    IconArrowRight,
  },
  LOGO: {
    IconBiohubLogo,
    IconCziLogo,
    LogoLockupColor,
    LogoMarkColor,
  },
  LOGO_REVERSED: {
    CZIDLogoReversed,
    LogoLockupReversed,
    LogoMarkReversed,
  },
};

const icons = Object.values(ICONS_TAXONOMY).reduce((result, components) => {
  return Object.assign(result, components);
}, {});

module.exports = Object.assign(icons, { ICONS_TAXONOMY });
