AllCops:
  Include:
    - '**/*.builder'
    - '**/*.fcgi'
    - '**/*.gemspec'
    - '**/*.god'
    - '**/*.jb'
    - '**/*.jbuilder'
    - '**/*.mspec'
    - '**/*.opal'
    - '**/*.pluginspec'
    - '**/*.podspec'
    - '**/*.rabl'
    - '**/*.rake'
    - '**/*.rbuild'
    - '**/*.rbw'
    - '**/*.rbx'
    - '**/*.ru'
    - '**/*.ruby'
    - '**/*.spec'
    - '**/*.thor'
    - '**/*.watchr'
    - '**/.irbrc'
    - '**/.pryrc'
    - '**/buildfile'
    - '**/config.ru'
    - '**/Appraisals'
    - '**/Berksfile'
    - '**/Brewfile'
    - '**/Buildfile'
    - '**/Capfile'
    - '**/Cheffile'
    - '**/Dangerfile'
    - '**/Deliverfile'
    - '**/Fastfile'
    - '**/*Fastfile'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Jarfile'
    - '**/Mavenfile'
    - '**/Podfile'
    - '**/Puppetfile'
    - '**/Rakefile'
    - '**/Snapfile'
    - '**/Thorfile'
    - '**/Vagabondfile'
    - '**/Vagrantfile'
  Exclude:
    - 'db/**/*'
    - vendor/**/*
    - bin/*

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

# This configuration was generated by
# `rubocop --auto-gen-config`
# on 2017-08-31 14:58:31 -0700 using RuboCop version 0.49.1.
# The point is for the user to remove these configuration records
# one by one as the offenses are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of RuboCop, may require this file to be generated again.

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: Include, TreatCommentsAsGroupSeparators.
# Include: **/Gemfile, **/gems.rb
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: with_first_parameter, with_fixed_indentation
Layout/AlignParameters:
  Exclude:
    - 'app/models/user.rb'

# Offense count: 3
# Cop supports --auto-correct.
Layout/EmptyLines:
  Exclude:
    - 'Gemfile'
    - 'bin/setup'
    - 'db/migrate/20170818200555_add_devise_to_users.rb'

# Offense count: 4
# Cop supports --auto-correct.
Layout/EmptyLinesAroundAccessModifier:
  Exclude:
    - 'app/controllers/pipeline_outputs_controller.rb'
    - 'app/controllers/projects_controller.rb'
    - 'app/controllers/samples_controller.rb'
    - 'app/controllers/users_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, no_empty_lines
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: normal, rails
Layout/IndentationConsistency:
  Exclude:
    - 'app/controllers/projects_controller.rb'
    - 'app/controllers/users_controller.rb'

# Offense count: 2
# Cop supports --auto-correct.
Layout/SpaceAfterColon:
  Exclude:
    - 'app/controllers/projects_controller.rb'
    - 'app/controllers/users_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SupportedStylesForEmptyBraces, SpaceBeforeBlockParameters.
# SupportedStyles: space, no_space
# SupportedStylesForEmptyBraces: space, no_space
Layout/SpaceInsideBlockBraces:
  Exclude:
    - 'db/seeds.rb'

# Offense count: 6
# Cop supports --auto-correct.
Layout/SpaceInsideBrackets:
  Exclude:
    - 'config/environments/dev.rb'
    - 'config/environments/production.rb'
    - 'config/environments/staging.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SupportedStylesForEmptyBraces.
# SupportedStyles: space, no_space, compact
# SupportedStylesForEmptyBraces: space, no_space
Layout/SpaceInsideHashLiteralBraces:
  Exclude:
    - 'test/controllers/samples_controller_test.rb'

# Offense count: 1
# Cop supports --auto-correct.
Layout/TrailingWhitespace:
  Exclude:
    - 'bin/setup'

# Offense count: 2
Lint/UselessAssignment:
  Exclude:
    - 'db/seeds.rb'

# Offense count: 115
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 300

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 100

# Offense count: 1
Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'

# Offense count: 1
# Configuration parameters: Include.
# Include: db/migrate/*.rb
Rails/ReversibleMigration:
  Exclude:
    - 'db/migrate/20170822205255_remove_password_digest_from_users.rb'

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

# Offense count: 32
Style/Documentation:
  Enabled: false

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: compact, expanded
Style/EmptyMethod:
  Exclude:
    - 'app/controllers/pipeline_outputs_controller.rb'
    - 'app/controllers/projects_controller.rb'
    - 'app/controllers/samples_controller.rb'
    - 'app/controllers/users_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: Strict.
Style/NumericLiterals:
  MinDigits: 15

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/spring.rb'

# Offense count: 134
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiteralsInInterpolation:
  Exclude:
    - 'bin/yarn'

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: MinSize, SupportedStyles.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

Style/GuardClause:
  Enabled: false