language: ruby
rvm:
- 2.4
notifications:
  slack:
    secure: gxnCeRv9OYVFwyxHaKDDa26u1KUryoh8HFLbKEHF2mbXek3EtwNac2imlPjNDyuCF/rYwb1jMkCECu6GUFHOzokoTTa4E0o2vihjvtTIDZxYNFVT6Oo2j+KVM/nJ1WFN4b1RxRdjNO+uuwpSFXGV6HKsvNbIbp13WRuQR0NXU6YrR0Eb/3RQi0GznGSR4JndgHfsBt6fxitZ8jvWj2iYOm8bnXffA4nqqNIeJ7YL9h6hApXPJrJpnPyYUGYdc2IKianTZP2ZBMy1U+sRjJP7ZT7XpiSdPmd+iTXXeukUy52kVvXfI4CDOdEoA8LHvfZuMEcQE03oRdk4Fm+zFyxdGPNeAbDUmTQoJxu6wiClYYGcHPJ1O/RSt7d/XQimSGouPS6zHPth6nKA3s0NblkQ9uOFoFDbqwmpRSn4OZlOS0WSJAP27gRAJkbGpEdJ+Cvfo13WGI47NoSD7bSQ92vEbUQ9nnaLFs85JElIzcYIsAlDm/bZThG3wMZah75JItt5CZWuV21gs5CyxnlZd+g8h0ItyPn8lfqXDSYIt2O143OqH58PB0FLQcG1PGmJCUl9eMhvnxyDcftc4j2Kc+mDFj+BrRdVfjYdcceJEDolUMdwcsa8I5x8Y94/50qwuWQEVK+Dr19FTXeuv4YRweNabu6wdvsuXiSa2llD28A+2/M=
