import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  overwrite: true,
  schema: "http://localhost:4444/graphql",
  documents: [
    "app/assets/src/**/*.ts",
    "!app/assets/src/gql/**/*",
    // Exclude files that are not part of the Apollo Server
    // TODO: (suzette) Find a way to generate a schema for these files
    "!app/assets/src/api/pathogen_lists.ts",
    "!app/assets/src/api/projects.ts",
    "!app/assets/src/api/samples.ts",
    "!app/assets/src/api/samples_reads_stats.ts",
    "!app/assets/src/api/user.ts",
    "!app/assets/src/components/views/discovery/api/quality_control.ts",
  ],
  ignoreNoDocuments: true, // for better experience with the watcher
  generates: {
    "app/assets/src/gql/generated/": {
      preset: "client",
      presetConfig: {
        fragmentMasking: false,
      },
      plugins: [
        {
          add: {
            content: [
              "// WARNING: This file is auto-generated by @graphql-codegen. To update this file, run `npm run codegen` from the root of this project.",
            ],
          },
        },
      ],
      hooks: { afterAllFileWrite: ["eslint --fix"] },
    },
},
};

export default config;
