# frozen_string_literal: true

# Generated by https://github.com/chanzuckerberg/idseq/blob/main/scripts/generate_host_genome.py

class AddHostGenomeTick < ActiveRecord::Migration[6.1]
  def up
    return unless HostGenome.find_by(name: "Tick")

    hg = HostGenome.find_by(name: "Tick")
    hg.name = "Tick"
    hg.s3_star_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/tick/2023-04-26/host-genome-generation-1/tick_STAR_genome.tar"
    hg.s3_bowtie2_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/tick/2023-04-26/host-genome-generation-1/tick.bowtie2.tar"
    hg.s3_minimap2_dna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/tick/2023-04-26/host-genome-generation-1/tick_dna.mmi"
    hg.s3_minimap2_rna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/tick/2023-04-26/host-genome-generation-1/tick_rna.mmi"
    hg.s3_hisat2_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/tick/2023-04-26/host-genome-generation-1/tick.hisat2.tar"
    hg.s3_kallisto_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/tick/2023-04-26/host-genome-generation-1/tick.kallisto.idx"
    hg.s3_bowtie2_index_path_v2 = "s3://#{S3_DATABASE_BUCKET}/host_filter/tick/2023-04-26/host-genome-generation-1/tick.bowtie2.tar"
    hg.skip_deutero_filter = 0 # this is set to 0 because the host is not a deuterostome

    hg.default_background_id = nil
    hg.save!
  end

  def down
    hg = HostGenome.find_by(name: "Tick")
    hg.s3_star_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/ticks/2017-09-01-utc-1504224000-unixtime__2017-09-01-utc-1504224000-unixtime/STAR_genome.tar"
    hg.s3_bowtie2_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/ticks/2017-09-01-utc-1504224000-unixtime__2017-09-01-utc-1504224000-unixtime/bowtie2_genome.tar"
    hg.s3_minimap2_dna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/ticks/2017-09-01-utc-1504224000-unixtime__2017-09-01-utc-1504224000-unixtime/ticks_minimap2_genome_dna.mmi"
    hg.s3_minimap2_rna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/ticks/2017-09-01-utc-1504224000-unixtime__2017-09-01-utc-1504224000-unixtime/ticks_minimap2_genome_rna.mmi"
    hg.s3_hisat2_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/ticks/20221031/hisat2_index_tar/ticks.hisat2.tar"
    hg.s3_kallisto_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/ticks/20221031/kallisto_idx/ticks.kallisto.idx"
    hg.s3_bowtie2_index_path_v2 = "s3://#{S3_DATABASE_BUCKET}/host_filter/ticks/20221031/bowtie2_index_tar/ticks.bowtie2.tar"
    hg.save! 
  end
end