# frozen_string_literal: true

# Generated by https://github.com/chanzuckerberg/idseq/blob/main/scripts/generate_host_genome.py

class AddHostGenomeOnchocercaVolvulus < ActiveRecord::Migration[6.1]
  def up
    return if HostGenome.find_by(name: "Onchocerca volvulus")

    hg = HostGenome.new
    hg.name = "Onchocerca volvulus"
    hg.s3_star_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/onchocerca_volvulus/2023-10-27/host-genome-generation-1/onchocerca_volvulus_STAR_genome.tar"
    hg.s3_bowtie2_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/onchocerca_volvulus/2023-10-27/host-genome-generation-1/onchocerca_volvulus.bowtie2.tar"
    hg.s3_minimap2_dna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/onchocerca_volvulus/2023-10-27/host-genome-generation-1/onchocerca_volvulus_dna.mmi"
    hg.s3_minimap2_rna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/onchocerca_volvulus/2023-10-27/host-genome-generation-1/onchocerca_volvulus_rna.mmi"
    hg.s3_hisat2_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/onchocerca_volvulus/2023-10-27/host-genome-generation-1/onchocerca_volvulus.hisat2.tar"
    hg.s3_kallisto_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/onchocerca_volvulus/2023-10-27/host-genome-generation-1/onchocerca_volvulus.kallisto.idx"
    hg.s3_bowtie2_index_path_v2 = "s3://#{S3_DATABASE_BUCKET}/host_filter/onchocerca_volvulus/2023-10-27/host-genome-generation-1/onchocerca_volvulus.bowtie2.tar"
    hg.skip_deutero_filter = 0 # this is set to 0 because the host is not a deuterostome

    hg.default_background_id = nil
    hg.save!
  end

  def down
    hg = HostGenome.find_by(name: "Onchocerca volvulus")
    hg.destroy! if hg
  end
end