# frozen_string_literal: true

# Generated by https://github.com/chanzuckerberg/idseq/blob/main/scripts/generate_host_genome.py

class AddHostGenomeGrayWhale < ActiveRecord::Migration[6.1]
  def up
    return if HostGenome.find_by(name: "Gray Whale")

    hg = HostGenome.new
    hg.name = "Gray Whale"
    hg.s3_star_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/gray_whale/2023-01-20/host-genome-generation-0/gray_whale_STAR_genome.tar"
    hg.s3_bowtie2_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/gray_whale/2023-01-20/host-genome-generation-0/gray_whale_bowtie2_genome.tar"
    hg.s3_minimap2_dna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/gray_whale/2023-01-20/host-genome-generation-0/gray_whale_minimap2_genome_dna.mmi"
    hg.s3_minimap2_rna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/gray_whale/2023-01-20/host-genome-generation-0/gray_whale_minimap2_genome_rna.mmi"
    hg.skip_deutero_filter = 1 # this is set to 1 because the host is a deuterostome

    hg.default_background_id = nil
    hg.save!
  end

  def down
    hg = HostGenome.find_by(name: "Gray Whale")
    hg.destroy! if hg
  end
end