# frozen_string_literal: true

# Generated by https://github.com/chanzuckerberg/idseq/blob/main/scripts/generate_host_genome.py

class AddHostGenomeOvisAries < ActiveRecord::Migration[6.1]
  def up
    return if HostGenome.find_by(name: "Ovis aries - sheep")

    hg = HostGenome.new
    hg.name = "Ovis aries - sheep"
    hg.s3_star_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/ovis_aries/2023-06-20/host-genome-generation-1/ovis_aries_STAR_genome.tar"
    hg.s3_bowtie2_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/ovis_aries/2023-06-20/host-genome-generation-1/ovis_aries.bowtie2.tar"
    hg.s3_minimap2_dna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/ovis_aries/2023-06-20/host-genome-generation-1/ovis_aries_dna.mmi"
    hg.s3_minimap2_rna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/ovis_aries/2023-06-20/host-genome-generation-1/ovis_aries_rna.mmi"
    hg.s3_hisat2_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/ovis_aries/2023-06-20/host-genome-generation-1/ovis_aries.hisat2.tar"
    hg.s3_kallisto_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/ovis_aries/2023-06-20/host-genome-generation-1/ovis_aries.kallisto.idx"
    hg.s3_bowtie2_index_path_v2 = "s3://#{S3_DATABASE_BUCKET}/host_filter/ovis_aries/2023-06-20/host-genome-generation-1/ovis_aries.bowtie2.tar"
    hg.skip_deutero_filter = 1 # this is set to 1 because the host is a deuterostome

    hg.default_background_id = nil
    hg.save!
  end

  def down
    hg = HostGenome.find_by(name: "Ovis aries - sheep")
    hg.destroy! if hg
  end
end