# frozen_string_literal: true

# Generated by https://github.com/chanzuckerberg/idseq/blob/main/scripts/generate_host_genome.py

class AddHostGenomeGorillaBeringei < ActiveRecord::Migration[6.1]
  def up
    return if HostGenome.find_by(name: "Gorilla beringei - eastern gorilla")

    hg = HostGenome.new
    hg.name = "Gorilla beringei - eastern gorilla"
    hg.s3_star_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/gorilla_beringei/2024-05-01/host-genome-generation-1/gorilla_beringei_STAR_genome.tar"
    hg.s3_bowtie2_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/gorilla_beringei/2024-05-01/host-genome-generation-1/gorilla_beringei.bowtie2.tar"
    hg.s3_minimap2_dna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/gorilla_beringei/2024-05-01/host-genome-generation-1/gorilla_beringei_dna.mmi"
    hg.s3_minimap2_rna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/gorilla_beringei/2024-05-01/host-genome-generation-1/gorilla_beringei_rna.mmi"
    hg.s3_hisat2_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/gorilla_beringei/2024-05-01/host-genome-generation-1/gorilla_beringei.hisat2.tar"
    hg.s3_kallisto_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/gorilla_beringei/2024-05-01/host-genome-generation-1/gorilla_beringei.kallisto.idx"
    hg.s3_bowtie2_index_path_v2 = "s3://#{S3_DATABASE_BUCKET}/host_filter/gorilla_beringei/2024-05-01/host-genome-generation-1/gorilla_beringei.bowtie2.tar"
    hg.skip_deutero_filter = 1 # this is set to 1 because the host is a deuterostome

    hg.default_background_id = nil
    hg.save!
  end

  def down
    hg = HostGenome.find_by(name: "Gorilla beringei - eastern gorilla")
    hg.destroy! if hg
  end
end