# frozen_string_literal: true

# Generated by https://github.com/chanzuckerberg/idseq/blob/main/scripts/generate_host_genome.py

class AddHostGenomeSalmoSalar < ActiveRecord::Migration[6.1]
  def up
    return if HostGenome.find_by(name: "Salmo salar - Atlantic salmon")

    hg = HostGenome.new
    hg.name = "Salmo salar - Atlantic salmon"
    hg.s3_star_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/salmo_salar/2024-03-25/host-genome-generation-1/salmo_salar_STAR_genome.tar"
    hg.s3_bowtie2_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/salmo_salar/2024-03-25/host-genome-generation-1/salmo_salar.bowtie2.tar"
    hg.s3_minimap2_dna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/salmo_salar/2024-03-25/host-genome-generation-1/salmo_salar_dna.mmi"
    hg.s3_minimap2_rna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/salmo_salar/2024-03-25/host-genome-generation-1/salmo_salar_rna.mmi"
    hg.s3_hisat2_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/salmo_salar/2024-03-25/host-genome-generation-1/salmo_salar.hisat2.tar"
    hg.s3_kallisto_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/salmo_salar/2024-03-25/host-genome-generation-1/salmo_salar.kallisto.idx"
    hg.s3_bowtie2_index_path_v2 = "s3://#{S3_DATABASE_BUCKET}/host_filter/salmo_salar/2024-03-25/host-genome-generation-1/salmo_salar.bowtie2.tar"
    hg.skip_deutero_filter = 1 # this is set to 1 because the host is a deuterostome

    hg.default_background_id = nil
    hg.save!
  end

  def down
    hg = HostGenome.find_by(name: "Salmo salar - Atlantic salmon")
    hg.destroy! if hg
  end
end