# frozen_string_literal: true

# Generated by https://github.com/chanzuckerberg/idseq/blob/main/scripts/generate_host_genome.py

class AddHostGenomeNeltumaPallidaKiawe < ActiveRecord::Migration[6.1]
  def up
    return if HostGenome.find_by(name: "Neltuma pallida - kiawe")

    hg = HostGenome.new
    hg.name = "Neltuma pallida - kiawe"
    hg.s3_star_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/neltuma_pallida_kiawe/2025-03-31/host-genome-generation-1/neltuma_pallida_kiawe_STAR_genome.tar"
    hg.s3_bowtie2_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/neltuma_pallida_kiawe/2025-03-31/host-genome-generation-1/neltuma_pallida_kiawe.bowtie2.tar"
    hg.s3_minimap2_dna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/neltuma_pallida_kiawe/2025-03-31/host-genome-generation-1/neltuma_pallida_kiawe_dna.mmi"
    hg.s3_minimap2_rna_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/neltuma_pallida_kiawe/2025-03-31/host-genome-generation-1/neltuma_pallida_kiawe_rna.mmi"
    hg.s3_hisat2_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/neltuma_pallida_kiawe/2025-03-31/host-genome-generation-1/neltuma_pallida_kiawe.hisat2.tar"
    hg.s3_kallisto_index_path = "s3://#{S3_DATABASE_BUCKET}/host_filter/neltuma_pallida_kiawe/2025-03-31/host-genome-generation-1/neltuma_pallida_kiawe.kallisto.idx"
    hg.s3_bowtie2_index_path_v2 = "s3://#{S3_DATABASE_BUCKET}/host_filter/neltuma_pallida_kiawe/2025-03-31/host-genome-generation-1/neltuma_pallida_kiawe.bowtie2.tar"
    hg.skip_deutero_filter = 0 # this is set to 0 because the host is not a deuterostome

    hg.default_background_id = nil
    hg.save!
  end

  def down
    hg = HostGenome.find_by(name: "Neltuma pallida (kiawe)")
    hg.destroy! if hg
  end
end
