default: &default
  adapter: mysql2
  username: root
  host: 127.0.0.1
  port: 3306
  database: idseq_<%= Rails.env %>
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: true

development:
  <<: *default
  host: db

test:
  <<: *default
  host: db

deployed: &deployed
  <<: *default
  host: <%= ENV['RDS_ADDRESS'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>

prod:
  <<: *deployed

staging:
  <<: *deployed

sandbox:
  <<: *deployed