default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: idseq_development

test:
  <<: *default
  database: idseq_test

staging:
  <<: *default
  host: <%= ENV['RDS_ADDRESS'] %>
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  host: <%= ENV['RDS_ADDRESS'] %>
