default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  host: 127.0.0.1
  port: 6033
  database: idseq_<%= Rails.env %>

development:
  <<: *default
  host: <%= ENV.include?("DOCKER") ? "db" : "127.0.0.1" %>

test:
  <<: *default
  username: <%= ENV.include?("CI") ? "travis" : "root" %>
  host: <%= ENV.include?("CI") ? "localhost" : "127.0.0.1" %>

dev:
  <<: *default
  username: idseqmaster
  host: <%= ENV['RDS_ADDRESS'] %>
  password: <%= ENV['DB_PASSWORD'] %>

staging:
  <<: *default
  username: idseqmaster
  host: <%= ENV['RDS_ADDRESS'] %>
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  host: <%= ENV['RDS_ADDRESS'] %>
