default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: 5
  database: idseq_<%= Rails.env %>

development:
  <<: *default
  host: <%= ENV.include?("DOCKER") ? "db" : "localhost" %>
  database: idseq_development

test:
  <<: *default
  host: localhost
  database: idseq_test

staging:
  <<: *default
  username: idseqmaster
  host: <%= ENV['RDS_ADDRESS'] %>
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  host: <%= ENV['RDS_ADDRESS'] %>
