default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  host: 127.0.0.1
  port: 6033
  database: idseq_<%= Rails.env %>

development:
  <<: *default
  host: <%= ENV.include?("DOCKER") ? "db" : "127.0.0.1" %>
  port: <%= ENV.include?("DOCKER") ? "3306" : 6033 %>

test:
  <<: *default
  port: <%= ENV.include?("CI") ? "3306" : 6033 %>

dev:
  <<: *default
  host: <%= ENV['RDS_ADDRESS'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME']

staging:
  <<: *default
  host: <%= ENV['RDS_ADDRESS'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME']

production:
  <<: *default
  host: <%= ENV['RDS_ADDRESS'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME']
