check_pipeline_run:
  cron: "*/10 * * * *"
  class: CheckPipelineRuns
  args:
  description: check pipeline runs every 10m

check_gsnapl_machines:
  cron: "*/10 * * * *"
  class: CheckGsnaplMachines
  args:
  description: check on GSNAPL machines every 10m
