# See: https://github.com/resque/resque-scheduler#static-schedules

SendSampleVisibilityEmail:
  cron: "0 0 20 * *"
  class: SendSampleVisibilityEmail
  queue: send_sample_visiblity_email
  description: "On the 20th of every month, run this job for sending upcoming sample visibility reminders."
