# See: https://github.com/resque/resque-scheduler#static-schedules
# Cron times are relative to config.time_zone.

HandleSfnNotificationsTimeout:
  every: 1h
  class: HandleSfnNotificationsTimeout
  queue: handle_sfn_notifications_timeout
  description: "This job checks for SFN executions that fail to update (get notified) after a maximum timeout period."
