# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 65a7f60b81e0becf08bff85b70a16768559e1737f37922d1807fe5d98ba45e9cf3b8ffcb64d313d0a4f8bae97e1b443c4020f5ea72c9d33984f822f4ccd4332e

test:
  secret_key_base: 5e9a3de728388328a66b622f9473edc0fb0559ae6b0c2e496f040353faa10b6152c902aa81898fedd235c7785d096a57701ba93760a37f7e4a84b4cf6c1b2632

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `prod:` environment over there.

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

prod:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

sandbox:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>