export interface AmrResult {
  contigCoverageBreadth: string | null;
  contigPercentId: string | null;
  contigs: string | null;
  contigSpecies: string | null;
  cutoff: string | null;
  dpm: number | null;
  drugClass: string | null;
  highLevelDrugClass: string | null;
  gene: string | null;
  geneFamily: string | null;
  mechanism: string | null;
  model: string | null;
  readCoverageBreadth: string | null;
  readCoverageDepth: string | null;
  reads: string | null;
  readSpecies: string | null;
  rpm: number | null;
}
