export const PUBLIC = "Public";
export const ANNOTATION = "Annotation";
export const LOCATION = "Location";
export const TIMEFRAME = "Timeframe";
export const VISIBILITY = "Visibility";
export const HOST = "Host";
export const SEARCH = "Search";
export const SAMPLE_TYPE = "Sample Type";
export const KLEBSIELLA = "Klebsiella";
export const TAXON = "taxon";
export const COMBOBOX = "combobox";
export const ADD_THRESHOLD = "+ ADD THRESHOLD";
export const NUMBERINPUT = 'input[type="number"]';
export const CHOOSE_TAXON = "Choose Taxon";
export const SAMPLE_NAME_SELECTOR = '[data-testid="sample-name"]';
export const ESCAPE = "Escape";
export const CLOSE_ICON = ".closeIcon-yEIIr";
export const LAST_MONTH = "Last Month";
export const LAST_THREE_MONTHS = "Last 3 Months";
export const LAST_SIX_MONTHS = "Last 6 Months";
export const LAST_WEEK = "Last Week";
export const PRIVATE = "Private";
export const OPTION = "option";
