# See https://docs.saucelabs.com/web-apps/automated-testing/playwright/#supported-testing-platforms for a list of supported versions.
# See https://docs.saucelabs.com/web-apps/automated-testing/playwright/yaml/#configfile for a list of supported configuration files.

apiVersion: v1alpha
kind: playwright
showConsoleLog: true
sauce:
  region: us-west-1
  concurrency: 5 
  metadata:
    tags:
      - e2e
      - czid
      - ci
    build: COMMIT $CI_COMMIT_SHORT_SHA
  tunnel:
    name: czid-github-sauce-connect 
playwright:
  version: package.json 
  configFile: ./ci.config.ts 
rootDir: ./
env:
  CZID_USERNAME: $CZID_USERNAME
  CZID_PASSWORD: $CZID_PASSWORD
suites:
  - name: "Chromium Mac"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['.home.spec.ts', '.landing-page.spec.ts', '.phylotree-taxon-sidebar.spec.ts', '.create-project.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
    shard: concurrency
artifacts:
  cleanup: true
  download:
    when: always
    match:
      - "*"
    directory: ./artifacts/
    