# See https://docs.saucelabs.com/web-apps/automated-testing/playwright/#supported-testing-platforms for a list of supported versions.
# See https://docs.saucelabs.com/web-apps/automated-testing/playwright/yaml/#configfile for a list of supported configuration files.

apiVersion: v1alpha
kind: playwright
showConsoleLog: true
sauce:
  region: us-west-1
  concurrency: 5 
  metadata:
    tags:
      - e2e
      - czid
      - $NODE_ENV
    build: COMMIT $CI_COMMIT_SHORT_SHA
  # comment out when running locally  
  # tunnel:
  #   name: czid-github-sauce-connect 
playwright:
  version: package.json 
  configFile: ./setup/$NODE_ENV.config.ts 
rootDir: ./
env:
  BASESPACE_USERNAME: $BASESPACE_USERNAME
  BASESPACE_PASSWORD: $BASESPACE_PASSWORD
  CZID_USERNAME: $CZID_USERNAME
  CZID_PASSWORD: $CZID_PASSWORD
  NODE_ENV: $NODE_ENV
suites:
  - name: "E2E: P-1: SNo e3: WGS SC2 Nanopore Sample Report & Download Data Validation"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/wgs/sample-report.spec.ts']
    maxDuration: 1h
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "SNo e3:"
      retries: 2
    shard: concurrency
  - name: "E2E: P-1: SNo e2: WGS SC2 Sample Report & Download Data Validation"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/wgs/sample-report.spec.ts']
    maxDuration: 1h
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "SNo e2:"
      retries: 2
    shard: concurrency
  - name: "E2E: P-1: SNo e1: WGS Sample Report & Download Data Validation"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/wgs/sample-report.spec.ts']
    maxDuration: 1h
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "SNo e1:"
      retries: 2
    shard: concurrency
  - name: "Functional: P-0: WGS - Sample upload (web) Basespace project: SNo 5: Basespace Viral Consensus Genome - No trim"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/wgs/sample-upload-basespace.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "SNo 5:"
      retries: 2
    shard: concurrency
  - name: "Functional: P-0: WGS - Sample upload (web) Basespace project: SNo 6: Basespace Viral Consensus Genome - with trim"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/wgs/sample-upload-basespace.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "SNo 6:"
      retries: 2
    shard: concurrency
  - name: "Functional: P-0: WGS - Sample upload (web) Basespace project: SNo 7: Basespace Viral Consensus Genome - No trim with mNGS - Ilumina"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/wgs/sample-upload-basespace.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "SNo 7:"
      retries: 2
    shard: concurrency
  - name: "Functional: P-0: WGS - Sample upload (web) Basespace project: SNo 8: Basespace Viral Consensus Genome - with trim with mNGS - Ilumina"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/wgs/sample-upload-basespace.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "SNo 8:"
      retries: 2
    shard: concurrency
  - name: "Functional: P-0: WGS - Sample upload: SNo 1: Viral Consensus Genome - No trim"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/wgs/sample-upload.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "SNo 1:"
      retries: 2
    shard: concurrency
  - name: "Functional: P-0: WGS - Sample upload: SNo 2: Viral Consensus Genome - with trim"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/wgs/sample-upload.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "SNo 2:"
      retries: 2
    shard: concurrency
  - name: "Functional: P-0: WGS - Sample upload: SNo 3: Viral Consensus Genome - No trim with mNGS - Ilumina"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/wgs/sample-upload.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "SNo 3:"
      retries: 2
    shard: concurrency
  - name: "Functional: P-0: WGS - Sample upload: SNo 4: Viral Consensus Genome - with trim with mNGS - Ilumina"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/wgs/sample-upload.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "SNo 4:"
      retries: 2
    shard: concurrency
artifacts:
  cleanup: true
  download:
    when: always
    match:
      - "*"
    directory: ./artifacts/
npm:
  dependencies:
    - adm-zip
    - moment-timezone
    - tar
    - fast-diff
