# See https://docs.saucelabs.com/web-apps/automated-testing/playwright/#supported-testing-platforms for a list of supported versions.
# See https://docs.saucelabs.com/web-apps/automated-testing/playwright/yaml/#configfile for a list of supported configuration files.

apiVersion: v1alpha
kind: playwright
showConsoleLog: true

# Test Config
suiteRetries: &suiteRetries 2
testRetries: &testRetries 3
testSettings: &testSettings
  platformName: "macOS 12"
  screenResolution: "1440x900"
  shard: concurrency
testParams: &testParams
  timeout: 10_800_000 # millisecond
  maxDuration: 3_600 # seconds
  browserName: "chromium"
  project: "chromium"
  retries: *testRetries
  
# Sauce Config
sauce:
  region: us-west-1
  concurrency: 5 
  retries: *suiteRetries
  metadata:
    tags:
      - e2e
      - czid
      - $NODE_ENV
    build: COMMIT $CI_COMMIT_SHORT_SHA
playwright:
  version: package.json 
  configFile: ./setup/$NODE_ENV.config.ts 
rootDir: ./
env:
  BASESPACE_USERNAME: $BASESPACE_USERNAME
  BASESPACE_PASSWORD: $BASESPACE_PASSWORD
  CZID_USERNAME: $CZID_USERNAME
  CZID_PASSWORD: $CZID_PASSWORD
  NODE_ENV: $NODE_ENV

suites:
  - name: "mNGS IP: Functional: P-0: mNGS-3: long mNGS Illumina sample Basespace upload"
    <<: *testSettings
    testMatch: ['tests/mngs/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "mNGS-3: long mNGS Illumina sample Basespace upload"
  - name: "mNGS IP: Functional: P-0: mNGS-2: short mNGS Illumina sample Basespace upload"
    <<: *testSettings
    testMatch: ['tests/mngs/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "mNGS-2: short mNGS Illumina sample Basespace upload"
  - name: "mNGS IP: Functional: P-0: mNGS-1: short mNGS Illumina sample web upload"
    <<: *testSettings
    testMatch: ['tests/mngs/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "mNGS-1: short mNGS Illumina sample web upload"
  - name: "Functional P-1: short mNGS - CG run: SNo 34: CG run kick off from short mNGS - OldIndex"
    <<: *testSettings
    testMatch: ['tests/consensusGenome/short-mngs.spec.ts']
    params:
      <<: *testParams
      grep: "SNo 34: CG run kick off from short mNGS - OldIndex"
  - name: "Functional P-1: short mNGS - CG run: SNo 35: CG run kick off from short mNGS - NewIndex"
    <<: *testSettings
    testMatch: ['tests/consensusGenome/short-mngs.spec.ts']
    params:
      <<: *testParams
      grep: "SNo 35: CG run kick off from short mNGS - NewIndex"
  - name: "Functional: P-0: SNo SC2-42: Project count when CG running from mNGS"
    <<: *testSettings
    testMatch: ['tests/sc2/cg-project-count.spec.ts']
    params:
      <<: *testParams
      grep: "SNo SC2-42: Project count when CG running from mNGS"
  - name: "Functional: P-0: Sample upload - SC2 Nanopore Midnight"
    <<: *testSettings
    testMatch: ['tests/sc2/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo SC2-4: SARS-CoV-2 Nanopore sample web upload"
  - name: "Functional: P-0: Sample upload - SC2 Nanopore Clear Labs"
    <<: *testSettings
    testMatch: ['tests/sc2/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo SC2-3: SARS-CoV-2 Nanopore sample web upload"
  - name: "Functional: P-0: Sample upload (web) with wetlab ARTIC v4/ARTIC v4.1"
    <<: *testSettings
    testMatch: ['tests/sc2/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo SC2-1: SARS-CoV-2 Illumina sample web upload with wetlab ARTIC v4/ARTIC v4.1"
  - name: "Functional: P-0: Sample upload (web) with wetlab ARTIC v5.3.2"
    <<: *testSettings
    testMatch: ['tests/sc2/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo SC2-1: SARS-CoV-2 Illumina sample web upload with wetlab ARTIC v5.3.2"
  - name: "Functional: P-0: Sample upload (web) with wetlab ARTIC v3"
    <<: *testSettings
    testMatch: ['tests/sc2/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo SC2-1: SARS-CoV-2 Illumina sample web upload with wetlab ARTIC v3$"
  - name: "Functional: P-0: Sample upload (web) with wetlab ARTIC v3 - Short Amplicons"
    <<: *testSettings
    testMatch: ['tests/sc2/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo SC2-1: SARS-CoV-2 Illumina sample web upload with wetlab ARTIC v3 - Short Amplicons"
  - name: "Functional: P-0: Sample upload (web) with wetlab MSSPE"
    <<: *testSettings
    testMatch: ['tests/sc2/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo SC2-1: SARS-CoV-2 Illumina sample web upload with wetlab MSSPE"
  - name: "Functional: P-0: Sample upload (web) with wetlab Combined MSSPE & ARTIC v3"
    <<: *testSettings
    testMatch: ['tests/sc2/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo SC2-1: SARS-CoV-2 Illumina sample web upload with wetlab Combined MSSPE & ARTIC v3"
  - name: "Functional: P-0: Sample upload (web) with wetlab SNAP"
    <<: *testSettings
    testMatch: ['tests/sc2/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo SC2-1: SARS-CoV-2 Illumina sample web upload with wetlab SNAP"
  - name: "Functional: P-0: Sample upload (web) with wetlab AmpliSeq"
    <<: *testSettings
    testMatch: ['tests/sc2/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo SC2-1: SARS-CoV-2 Illumina sample web upload with wetlab AmpliSeq"
  - name: "Functional: P-0: Sample upload (web) with wetlab COVIDseq"
    <<: *testSettings
    testMatch: ['tests/sc2/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo SC2-1: SARS-CoV-2 Illumina sample web upload with wetlab COVIDseq"
  - name: "Functional: P-0: Sample upload (web) with wetlab VarSkip"
    <<: *testSettings
    testMatch: ['tests/sc2/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo SC2-1: SARS-CoV-2 Illumina sample web upload with wetlab VarSkip"
  - name: "Functional: P-0: Sample upload (web) with wetlab Midnight"
    <<: *testSettings
    testMatch: ['tests/sc2/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo SC2-1: SARS-CoV-2 Illumina sample web upload with wetlab Midnight"
  - name: "Functional: P-0: Sample upload (web) with wetlab Easyseq"
    <<: *testSettings
    testMatch: ['tests/sc2/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo SC2-1: SARS-CoV-2 Illumina sample web upload with wetlab Easyseq"
  - name: "E2E: P-1: SNo e3: WGS SC2 Nanopore Sample Report & Download Data Validation"
    <<: *testSettings
    testMatch: ['tests/wgs/sample-report.spec.ts']
    params:
      <<: *testParams
      grep: "SNo e3:"
  - name: "E2E: P-1: SNo e2: WGS SC2 Sample Report & Download Data Validation"
    <<: *testSettings
    testMatch: ['tests/wgs/sample-report.spec.ts']
    params:
      <<: *testParams
      grep: "SNo e2:"
  - name: "E2E: P-1: SNo e1: WGS Sample Report & Download Data Validation"
    <<: *testSettings
    testMatch: ['tests/wgs/sample-report.spec.ts']
    params:
      <<: *testParams
      grep: "SNo e1:"
  - name: "Functional: P-0: WGS - Sample upload (web) Basespace project: SNo 5: Basespace Viral Consensus Genome - No trim"
    <<: *testSettings
    testMatch: ['tests/wgs/sample-upload-basespace.spec.ts']
    params:
      <<: *testParams
      grep: "SNo 5:"
  - name: "Functional: P-0: WGS - Sample upload (web) Basespace project: SNo 6: Basespace Viral Consensus Genome - with trim"
    <<: *testSettings
    testMatch: ['tests/wgs/sample-upload-basespace.spec.ts']
    params:
      <<: *testParams
      grep: "SNo 6:"
  - name: "Functional: P-0: WGS - Sample upload (web) Basespace project: SNo 7: Basespace Viral Consensus Genome - No trim with mNGS - Ilumina"
    <<: *testSettings
    testMatch: ['tests/wgs/sample-upload-basespace.spec.ts']
    params:
      <<: *testParams
      grep: "SNo 7:"
  - name: "Functional: P-0: WGS - Sample upload (web) Basespace project: SNo 8: Basespace Viral Consensus Genome - with trim with mNGS - Ilumina"
    <<: *testSettings
    testMatch: ['tests/wgs/sample-upload-basespace.spec.ts']
    params:
      <<: *testParams
      grep: "SNo 8:"
  - name: "Functional: P-0: WGS - Sample upload: SNo 1: Viral Consensus Genome - No trim"
    <<: *testSettings
    testMatch: ['tests/wgs/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo 1:"
  - name: "Functional: P-0: WGS - Sample upload: SNo 2: Viral Consensus Genome - with trim"
    <<: *testSettings
    testMatch: ['tests/wgs/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo 2:"
  - name: "Functional: P-0: WGS - Sample upload: SNo 3: Viral Consensus Genome - No trim with mNGS - Ilumina"
    <<: *testSettings
    testMatch: ['tests/wgs/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo 3:"
  - name: "Functional: P-0: WGS - Sample upload: SNo 4: Viral Consensus Genome - with trim with mNGS - Ilumina"
    <<: *testSettings
    testMatch: ['tests/wgs/sample-upload.spec.ts']
    params:
      <<: *testParams
      grep: "SNo 4:"
artifacts:
  cleanup: true
  download:
    when: always
    match:
      - "*"
    directory: ./artifacts/
npm:
  dependencies:
    - adm-zip
    - moment-timezone
    - tar
    - fast-diff
