# See https://docs.saucelabs.com/web-apps/automated-testing/playwright/#supported-testing-platforms for a list of supported versions.
# See https://docs.saucelabs.com/web-apps/automated-testing/playwright/yaml/#configfile for a list of supported configuration files.

apiVersion: v1alpha
kind: playwright
showConsoleLog: true
sauce:
  region: us-west-1
  concurrency: 5 
  metadata:
    tags:
      - e2e
      - czid
      - staging
    build: COMMIT $CI_COMMIT_SHORT_SHA
  # comment out when running locally  
  # tunnel:
  #   name: czid-github-sauce-connect 
playwright:
  version: package.json 
  configFile: ./staging.config.ts 
rootDir: ./
env:
  CZID_USERNAME: $CZID_USERNAME
  CZID_PASSWORD: $CZID_PASSWORD
  NODE_ENV: $NODE_ENV
suites:
  - name: "Chromium Mac"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['.*.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
    shard: concurrency
artifacts:
  cleanup: true
  download:
    when: always
    match:
      - "*"
    directory: ./artifacts/    
