# See https://docs.saucelabs.com/web-apps/automated-testing/playwright/#supported-testing-platforms for a list of supported versions.
# See https://docs.saucelabs.com/web-apps/automated-testing/playwright/yaml/#configfile for a list of supported configuration files.

apiVersion: v1alpha
kind: playwright
showConsoleLog: true
sauce:
  region: us-west-1
  concurrency: 5 
  metadata:
    tags:
      - e2e
      - czid
      - staging
    build: COMMIT $CI_COMMIT_SHORT_SHA
  # comment out when running locally  
  # tunnel:
  #   name: czid-github-sauce-connect 
playwright:
  version: package.json 
  configFile: ./setup/staging.config.ts
rootDir: ./
env:
  CZID_USERNAME: $CZID_USERNAME
  CZID_PASSWORD: $CZID_PASSWORD
  NODE_ENV: $NODE_ENV
suites:
  - name: "Functional: P-0"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/wgs/sample-upload.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "Functional: P-0"
      retries: 2
    shard: concurrency
  - name: "Data Validation: P-0"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/wgs/report-files.spec.ts', 'wgs/sample-report-values-and-data-type.spec.ts', 'wgs/sample-report.spec.ts', 'wgs/sample-upload-error-handling.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "Data Validation: P-0"
      retries: 2
    shard: concurrency
  - name: "Bulk Download: AMR"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/download/bulk-download-amr-smoke.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "Smoke Test: "
      retries: 2
    shard: concurrency
  - name: "Bulk Download: LMNGS"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/download/bulk-download-lmngs-smoke.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "Smoke Test: "
      retries: 3
    shard: concurrency
  - name: "Bulk Download: MNGS"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/download/bulk-download-mngs-smoke.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "Smoke Test: "
      retries: 3
    shard: concurrency
  - name: "Bulk Download: WGS"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/download/bulk-download-wgs-smoke.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "Smoke Test: "
      retries: 2
    shard: concurrency
  - name: "Pipeline Visualization"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/view/pipeline-visualization-smoke.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "Smoke Test: "
      retries: 1
    shard: concurrency
  - name: "Sample Deletion Smoke Tests"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/sample/sample-deletion-smoke.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "Smoke Test: "
      retries: 3
    shard: concurrency
  - name: "Sample Report Filter Smoke Tests"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/sampleReport/sample-report-filters.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "Smoke Test: "
      retries: 3
    shard: concurrency
  - name: "Sample Upload Smoke Tests"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/upload/upload-smoke.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "Smoke Test: "
      retries: 3
    shard: concurrency
  - name: "Coverage Viz Smoke Tests"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/sampleReport/sample-report-coverage-viz.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "Smoke Test: "
      retries: 3
    shard: concurrency
  - name: "Sample Heatmap"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: ['tests/sample/sample-heatmap-smoke.spec.ts']
    params:
      browserName: "chromium"
      project: "chromium"
      grep: "Smoke Test: "
      retries: 1
    shard: concurrency
artifacts:
  cleanup: true
  download:
    when: always
    match:
      - "*"
    directory: ./artifacts/
npm:
  dependencies:
    - adm-zip
