name: idseq-web build Docker image

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

env:
  AWS_DEFAULT_OUTPUT: json
  DEBIAN_FRONTEND: noninteractive
  LC_ALL: C.UTF-8
  LANG: C.UTF-8
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  IMDS_URL: http://169.254.169.254/latest

jobs:
  cancel_outdated_builds:
    runs-on: ubuntu-latest
    # This will cancel the whole workflow for non-current pushes on your branch
    steps:
      - name: Cancel Outdated Builds
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
  build_dev_docker_image:
    runs-on: [self-hosted, idseq-dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{runner.os}}-cache
      - name: Build and push Docker images
        run: |
          sudo apt-get -q install --yes awscli
          export token=$(curl -s -X PUT $IMDS_URL/api/token -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
          export AWS_REGION=$(curl -s -H "X-aws-ec2-metadata-token: $token" $IMDS_URL/dynamic/instance-identity/document | jq -r .region)
          export AWS_ACCOUNT_ID=$(aws sts get-caller-identity | jq -r .Account)
          $(aws ecr get-login --no-include-email)
          bin/build-docker $(basename $GITHUB_REF) ${GITHUB_SHA::8}
          bin/push-docker $(basename $GITHUB_REF) ${GITHUB_SHA::8}
  build_prod_docker_image:
    runs-on: [self-hosted, idseq-prod]
    steps:
      - name: Cleanup
        run: sudo chown -R $USER:$USER /opt/actions-runner/_work/czid-web-private/czid-web-private
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{runner.os}}-cache
      - name: Build and push Docker images
        run: |
          sudo apt-get -q install --yes awscli
          export token=$(curl -s -X PUT $IMDS_URL/api/token -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
          export AWS_REGION=$(curl -s -H "X-aws-ec2-metadata-token: $token" $IMDS_URL/dynamic/instance-identity/document | jq -r .region)
          export AWS_ACCOUNT_ID=$(aws sts get-caller-identity | jq -r .Account)
          $(aws ecr get-login --no-include-email)
          bin/build-docker $(basename $GITHUB_REF) ${GITHUB_SHA::8}
          bin/push-docker $(basename $GITHUB_REF) ${GITHUB_SHA::8}
