name: Deploy

on:
  workflow_dispatch:
    inputs:
      source:
        description: Source branch you want to deploy changes from
        required: true
      destination:
        description: Destination branch you want to deploy to (e.g. sandbox)
        required: true
      release_notes:
        description: Reason for the release (scheduled, hotfix, issue ID, etc.)
        required: true
      force:
        description: Force release (set to `true` to release even if checks fail)
        default: 'false'
env:
  AWS_DEFAULT_OUTPUT: json
  AWS_REGION: us-west-2
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

run-name: Deploy ${{ github.event.inputs.source }} to ${{ github.event.inputs.destination }}

jobs:
  run_deployment:
    name: Deploy ${{ github.event.inputs.source }} to ${{ github.event.inputs.destination }}
    uses: ./.github/workflows/reusable-deploy-workflow.yml
    with:
      source: ${{ github.event.inputs.source }}
      destination: ${{ github.event.inputs.destination }}
      force: ${{ github.event.inputs.force == 'true' }}
      developer_name: ${{ github.actor }}
      deployment_reason: ${{ github.event.inputs.release_notes }}

  run_staging_playwright_e2e_tests:
    if: ${{ github.event.inputs.destination == 'staging' }}
    name: Run Playwright E2E tests on staging
    needs: run_deployment
    uses: ./.github/workflows/e2e-automation.yml
    with:
      node-environment: "staging"
      test-category: "smoke"
      should-run-with-feature-flags: "false"
    secrets: inherit
