name: e2e-staging-tests

on:
  workflow_call:
    
env:
  AWS_DEFAULT_OUTPUT: json
  AWS_REGION: us-west-2
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  EXECUTOR_ROLE: czid-staging-gh-actions-executor

jobs:
  cancel_outdated_builds:
    runs-on: ubuntu-latest
    # This will cancel the whole workflow for non-current pushes on your branch
    steps:
      - name: Cancel Outdated Builds
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
  
  e2e-tests:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run e2e tests
        uses: ./.github/workflows/reusable-e2e-tests.yml
        with:
          environment: staging
