name: idseq-web pull-request-only
on:
  - pull_request

jobs:
  sastisfaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: chanzuckerberg/sastisfaction
          ref: main
          path: .github/actions/sastisfaction
          ssh-key: ${{ secrets.SASTISFACTION_READ_KEY }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker pull
        run: docker pull ghcr.io/chanzuckerberg/sastisfaction:main
      - name: Run SASTisfaction
        uses: ./.github/actions/sastisfaction
        with:
          snowflake_private_key: ${{ secrets.SASTISFACTION_RSA_KEY }}

  brakeman:
    # This action is for inline GitHub diff annotations via ReviewDog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ReviewDog Brakeman
        uses: reviewdog/action-brakeman@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
