name: idseq-web sentry release

on:
  deployment

jobs:
  sentry-release:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: czi-idseq
      SENTRY_URL: https://sentry.prod.si.czi.technology
      SENTRY_ENV: ${{ github.event.deployment.environment }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: ".node-version"
    - name: Cache Node Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install older version of npm
      run: npm install -g npm@v8.5.5
    - name: Install dependencies
      run: |
        npm install
        npm install -g @sentry/cli
    - name: Build Webpack config for source maps
      run: npm run build-img
    - name: Notify Sentry about the latest release
      run: |
        start=$(date +%s)
        sentry-cli releases new --project idseq-backend --project idseq-frontend "${GITHUB_SHA::8}"
        sentry-cli releases --project idseq-frontend files "${GITHUB_SHA::8}" upload-sourcemaps app/assets/dist --no-rewrite
        sentry-cli releases finalize "${GITHUB_SHA::8}"
        now=$(date +%s)
        sentry-cli releases deploys "${GITHUB_SHA::8}" new --env $SENTRY_ENV -t $((now-start))
