name: idseq-web sentry release

on:
  push:
    branches:
      - staging
      - prod

jobs:
  sentry-release:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: czi-idseq
      SENTRY_URL: https://sentry.prod.si.czi.technology
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Cache Node Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: |
        npm install
        npm install -g @sentry/cli
    - name: Build Webpack config for source maps
      run: npm run build-img
    - name: Set environment
      run: echo "ENV=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Notify Sentry about the latest release
      run: |
        start=$(date +%s)
        sentry-cli releases new --project idseq-backend --project idseq-frontend "${GITHUB_SHA::8}"
        sentry-cli releases --project idseq-frontend files "${GITHUB_SHA::8}" upload-sourcemaps app/assets/dist --no-rewrite
        sentry-cli releases finalize "${GITHUB_SHA::8}"
        now=$(date +%s)
        sentry-cli releases deploys "${GITHUB_SHA::8}" new -e $ENV -t $((now-start))
