name: czid-web sync tasks

on:
  push:
    branches: main

jobs:
  sync_repo:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync repository mirrors
        run: |
          git fetch --unshallow
          eval $(ssh-agent)
          echo "${{secrets.IDSEQ_WEB_SYNC}}" | ssh-add -
          git remote add czid-web git@github.com:chanzuckerberg/czid-web.git
          git push --force czid-web $(basename $GITHUB_REF)
