name: idseq-web sync tasks

on:
  push:
    branches:
      main

jobs:
  sync_repo:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync repository mirrors
        run: |
          git fetch --unshallow
          eval $(ssh-agent)
          echo "${{secrets.IDSEQ_WEB_SYNC}}" | ssh-add -
          git remote add idseq-web git@github.com:chanzuckerberg/idseq-web.git
          git push --force idseq-web $(basename $GITHUB_REF)
