name: Track Typescript Conversion

on:
  push:
    branches:
      - main

jobs:
  track-typescript-conversion:
    runs-on: [self-hosted, idseq-dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: Install script dependencies
        run: |
          apt-get -qq update
          apt-get -qq install -o=Dpkg::Use-Pty=0 --yes curl awscli jq

          export token=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
          export AWS_DEFAULT_REGION=$(curl -s -H "X-aws-ec2-metadata-token: $token" http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
          aws configure set default.region $AWS_DEFAULT_REGION
      - name: Publish AWS CloudWatch metric about .js, .jsx, .ts, and .tsx file counts
        run: |
          js_file_count=$(grep \
            --recursive \
            --files-with-matches \
            --include '*.js' \
            --include '*.jsx' \
            --exclude 'app/assets/config/manifest.js' \
            --exclude 'app/assets/javascripts/application.js' \
            ' ' \
            app |
            wc -l)

          ts_file_count=$(grep \
                --recursive \
                --files-with-matches \
                --include '*.ts' \
                --include '*.tsx' \
                ' ' \
                app |
                wc -l)

          aws cloudwatch put-metric-data --metric-name JavascriptFileCount --namespace TypescriptConversion --value $js_file_count
          aws cloudwatch put-metric-data --metric-name TypescriptFileCount --namespace TypescriptConversion --value $ts_file_count
