name: Track Typescript Conversion

on:
  push:
    branches:
      - main

jobs:
  track-typescript-conversion:
    runs-on: ubuntu-latest
    permissions: # these permissions must be set for AWS auth to work!
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "main"
      - name: Configure AWS Credentials
        id: configure_aws_credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.DEV_AWS_ROLE }}
          role-session-name: build-push-docker-img
      - name: Publish AWS CloudWatch metric about .js, .jsx, .ts, and .tsx file counts
        run: |
          js_file_count=$(grep \
            --recursive \
            --files-with-matches \
            --include '*.js' \
            --include '*.jsx' \
            --exclude 'app/assets/config/manifest.js' \
            --exclude 'app/assets/javascripts/application.js' \
            --exclude 'app/assets/webassembly/htsfile.js' \
            --exclude 'app/assets/dist/main.bundle.min.js'\
            --exclude 'app/assets/dist/vendors.bundle.min.js'\
            --exclude 'app/assets/webassembly/seqtk.js' \
            ' ' \
            app |
            wc -l)

          ts_file_count=$(grep \
                --recursive \
                --files-with-matches \
                --include '*.ts' \
                --include '*.tsx' \
                ' ' \
                app |
                wc -l)

          fix_me_count=$(grep \
                --recursive \
                --include '*.ts' \
                --include '*.tsx' \
                -o \
                '$TSFixMe' \
                app |
                wc -l)

          expect_error_count=$(grep \
                --recursive \
                --include '*.ts' \
                --include '*.tsx' \
                -o \
                '@ts-expect-error' \
                app |
                wc -l)

          aws cloudwatch put-metric-data --metric-name JavascriptFileCount --namespace TypescriptConversion --value $js_file_count
          aws cloudwatch put-metric-data --metric-name TypescriptFileCount --namespace TypescriptConversion --value $ts_file_count
          aws cloudwatch put-metric-data --metric-name TSFixMeCount --namespace TypescriptConversion --value $fix_me_count
          aws cloudwatch put-metric-data --metric-name TSExpectErrorCount --namespace TypescriptConversion --value $expect_error_count
